### ISSUE TITLE
fix: frontend is doing chemical calculations for the backend

### ISSUE THREAD

**Issue by FredrikMWold** [equinor/chemcom-api#2]
The frontend is doing chemical calculation for the plant reservoirs.
The calculation are being done in: /home/fredrik/equinor/chemcom/src/ChemDec.Ui/ClientApp/src/components/Plant/Dashboard/index.js

Look into moving these calculation to backend.

Endpoints:
- https://chemdec-dev.azurewebsites.net/api/shipment/graph?from=2022-11-21T11%3A12%3A31.189Z&toInstallationId=c4d2d827-48e6-45a8-9fb4-dbd8e7a54a67&timeZone=W.%20Europe%20Standard%20Time&groupBy=total
- https://chemdec-dev.azurewebsites.net/api/installation/reservoir/c4d2d827-48e6-45a8-9fb4-dbd8e7a54a67

**Comment by ashukequinor** [comment]
We have added chemical calculation logic in backed when adding shipment against below task

#189 

and the endpoints provided in description of the bug is using already calculated value from database so I think we don't need to change anything in backend for this issue.

@vehecap  @spatrE01  @SupraEQNR  @shivaji7507
